# Generated by Django 3.0 on 2022-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/%Y/%m/%d/'),
        ),
    ]
