# Generated by Django 3.0 on 2022-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
