# Generated by Django 3.0 on 2022-07-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0009_auto_20220712_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
