# Generated by Django 3.0 on 2022-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0020_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
