# Generated by Django 3.0 on 2022-07-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0022_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='geekish.Post'),
        ),
    ]
