# Generated by Django 3.0 on 2022-07-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0025_auto_20220719_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
