# Generated by Django 3.0 on 2022-07-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0027_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
