# Generated by Django 3.0 on 2022-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0030_auto_20220720_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='static/img/'),
        ),
    ]
