# Generated by Django 3.0 on 2022-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0031_auto_20220722_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
