# Generated by Django 3.0 on 2022-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0032_remove_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='static/img/'),
        ),
    ]
