# Generated by Django 3.0 on 2022-07-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0033_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
