# Generated by Django 3.0 on 2022-07-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0036_auto_20220728_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
