# Generated by Django 3.0 on 2022-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0038_auto_20220801_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='post',
            name='p_topic_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='p_topic_2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='p_topic_3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='p_topic_4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
    ]
