# Generated by Django 3.0 on 2022-08-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0042_auto_20220818_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
