# Generated by Django 3.0 on 2022-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0044_post_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urls',
            field=models.SlugField(max_length=200),
        ),
    ]
