# Generated by Django 3.0 on 2022-08-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0045_auto_20220818_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='urls',
            new_name='url',
        ),
    ]
