# Generated by Django 3.0 on 2022-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0047_auto_20220818_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
