# Generated by Django 3.0 on 2022-08-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0049_auto_20220826_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='geekish.Post'),
        ),
    ]
