# Generated by Django 3.0 on 2022-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0052_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
