# Generated by Django 3.0 on 2022-09-02 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0053_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='p_topic_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p_topic_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p_topic_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p_topic_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='paragraph_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekish.Post')),
            ],
        ),
        migrations.CreateModel(
            name='LinkName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekish.Link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='geekish.Paragraph'),
        ),
    ]
