# Generated by Django 3.0 on 2022-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekish', '0055_auto_20220902_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
